/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenuesVenueIdRouteImport } from './routes/venues/$venueId'
import { Route as EventsEventIdRouteRouteImport } from './routes/events/$eventId/route'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as EventsEventIdStandsRouteImport } from './routes/events/$eventId/stands'
import { Route as EventsEventIdPavilhaoRouteImport } from './routes/events/$eventId/pavilhao'
import { Route as EventsEventIdFinancasRouteImport } from './routes/events/$eventId/financas'
import { Route as EventsEventIdDashboardRouteImport } from './routes/events/$eventId/dashboard'
import { Route as EventsEventIdComercialRouteImport } from './routes/events/$eventId/comercial'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenueIdRoute = VenuesVenueIdRouteImport.update({
  id: '/venues/$venueId',
  path: '/venues/$venueId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRouteRoute = EventsEventIdRouteRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsEventIdRouteRoute,
} as any)
const EventsEventIdStandsRoute = EventsEventIdStandsRouteImport.update({
  id: '/stands',
  path: '/stands',
  getParentRoute: () => EventsEventIdRouteRoute,
} as any)
const EventsEventIdPavilhaoRoute = EventsEventIdPavilhaoRouteImport.update({
  id: '/pavilhao',
  path: '/pavilhao',
  getParentRoute: () => EventsEventIdRouteRoute,
} as any)
const EventsEventIdFinancasRoute = EventsEventIdFinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => EventsEventIdRouteRoute,
} as any)
const EventsEventIdDashboardRoute = EventsEventIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EventsEventIdRouteRoute,
} as any)
const EventsEventIdComercialRoute = EventsEventIdComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => EventsEventIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRouteRouteWithChildren
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/events/$eventId/comercial': typeof EventsEventIdComercialRoute
  '/events/$eventId/dashboard': typeof EventsEventIdDashboardRoute
  '/events/$eventId/financas': typeof EventsEventIdFinancasRoute
  '/events/$eventId/pavilhao': typeof EventsEventIdPavilhaoRoute
  '/events/$eventId/stands': typeof EventsEventIdStandsRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/events/$eventId/comercial': typeof EventsEventIdComercialRoute
  '/events/$eventId/dashboard': typeof EventsEventIdDashboardRoute
  '/events/$eventId/financas': typeof EventsEventIdFinancasRoute
  '/events/$eventId/pavilhao': typeof EventsEventIdPavilhaoRoute
  '/events/$eventId/stands': typeof EventsEventIdStandsRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRouteRouteWithChildren
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/events/$eventId/comercial': typeof EventsEventIdComercialRoute
  '/events/$eventId/dashboard': typeof EventsEventIdDashboardRoute
  '/events/$eventId/financas': typeof EventsEventIdFinancasRoute
  '/events/$eventId/pavilhao': typeof EventsEventIdPavilhaoRoute
  '/events/$eventId/stands': typeof EventsEventIdStandsRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/$eventId'
    | '/venues/$venueId'
    | '/events/$eventId/comercial'
    | '/events/$eventId/dashboard'
    | '/events/$eventId/financas'
    | '/events/$eventId/pavilhao'
    | '/events/$eventId/stands'
    | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/venues/$venueId'
    | '/events/$eventId/comercial'
    | '/events/$eventId/dashboard'
    | '/events/$eventId/financas'
    | '/events/$eventId/pavilhao'
    | '/events/$eventId/stands'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/events/$eventId'
    | '/venues/$venueId'
    | '/events/$eventId/comercial'
    | '/events/$eventId/dashboard'
    | '/events/$eventId/financas'
    | '/events/$eventId/pavilhao'
    | '/events/$eventId/stands'
    | '/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsEventIdRouteRoute: typeof EventsEventIdRouteRouteWithChildren
  VenuesVenueIdRoute: typeof VenuesVenueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$venueId': {
      id: '/venues/$venueId'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof VenuesVenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof EventsEventIdRouteRoute
    }
    '/events/$eventId/stands': {
      id: '/events/$eventId/stands'
      path: '/stands'
      fullPath: '/events/$eventId/stands'
      preLoaderRoute: typeof EventsEventIdStandsRouteImport
      parentRoute: typeof EventsEventIdRouteRoute
    }
    '/events/$eventId/pavilhao': {
      id: '/events/$eventId/pavilhao'
      path: '/pavilhao'
      fullPath: '/events/$eventId/pavilhao'
      preLoaderRoute: typeof EventsEventIdPavilhaoRouteImport
      parentRoute: typeof EventsEventIdRouteRoute
    }
    '/events/$eventId/financas': {
      id: '/events/$eventId/financas'
      path: '/financas'
      fullPath: '/events/$eventId/financas'
      preLoaderRoute: typeof EventsEventIdFinancasRouteImport
      parentRoute: typeof EventsEventIdRouteRoute
    }
    '/events/$eventId/dashboard': {
      id: '/events/$eventId/dashboard'
      path: '/dashboard'
      fullPath: '/events/$eventId/dashboard'
      preLoaderRoute: typeof EventsEventIdDashboardRouteImport
      parentRoute: typeof EventsEventIdRouteRoute
    }
    '/events/$eventId/comercial': {
      id: '/events/$eventId/comercial'
      path: '/comercial'
      fullPath: '/events/$eventId/comercial'
      preLoaderRoute: typeof EventsEventIdComercialRouteImport
      parentRoute: typeof EventsEventIdRouteRoute
    }
  }
}

interface EventsEventIdRouteRouteChildren {
  EventsEventIdComercialRoute: typeof EventsEventIdComercialRoute
  EventsEventIdDashboardRoute: typeof EventsEventIdDashboardRoute
  EventsEventIdFinancasRoute: typeof EventsEventIdFinancasRoute
  EventsEventIdPavilhaoRoute: typeof EventsEventIdPavilhaoRoute
  EventsEventIdStandsRoute: typeof EventsEventIdStandsRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

const EventsEventIdRouteRouteChildren: EventsEventIdRouteRouteChildren = {
  EventsEventIdComercialRoute: EventsEventIdComercialRoute,
  EventsEventIdDashboardRoute: EventsEventIdDashboardRoute,
  EventsEventIdFinancasRoute: EventsEventIdFinancasRoute,
  EventsEventIdPavilhaoRoute: EventsEventIdPavilhaoRoute,
  EventsEventIdStandsRoute: EventsEventIdStandsRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}

const EventsEventIdRouteRouteWithChildren =
  EventsEventIdRouteRoute._addFileChildren(EventsEventIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsEventIdRouteRoute: EventsEventIdRouteRouteWithChildren,
  VenuesVenueIdRoute: VenuesVenueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
